name: Docker ci pipeline
run-name: ${{github.actor }} is running
on: [push]
jobs:
   docker-ci-pipeline:
      runs-on: ubuntu-latest
      steps:
         - name: Docker build
           run: docker build -t ${{secrets.username}}/flask-hello-world .

         - name: Checkout Repository
           uses: actions/checkout@v4

         - name: Docker push
           run: echo "Documentation in Github wiki"

         - name: Docker push
           run: echo "Documentation in Github wiki"
           
